### ISSUE TITLE
Allow Doug to commit

### ISSUE THREAD

**Issue by dsblank** [jashapiro/BioCS#1]
I don't think I can commit... I'm getting the error:

```
$ git push                                                                                                 
error: The requested URL returned error: 403 Forbidden while accessing https://github.com/jashapiro/BioCS.git/info/refs            

fatal: HTTP request failed    
```

Do I need to be an admin or something? BTW, I'm on athena.... I haven't used git on athena to push commits yet.

**Comment by jashapiro** [comment]
I don't think there is anything more I can do on the github end. I believe you should have commit permissions. Perhaps try a commit on the github website?

I've had trouble in the past with the https connection (possibly on athena...) You might try using ssh with a manually added key.
